### ISSUE TITLE
zerodb template fail to keep the listening port of the zerodb process up to date

### ISSUE THREAD

**Issue by zaibon** [threefoldtech/0-templates#102]
I notice that sometime when I try to interact with some zerodb, I get an Access denied error.
After investigation it turns out that it's because the zerodb template have an outdated `nodePort` in its data  which make it try to reach another zdb then the one intended, thus the a wrong password. This explain the access denied error.

**Comment by zaibon** [comment]
Problems comes from the monitor action:
https://github.com/threefoldtech/0-templates/blob/d03401be880351c26cfa0814ae7fce272a1a3f18/templates/zerodb/zerodb.py#L53-L55

here we see that is the zerodb is down, we try to restart it. It can be down for 2 reason:
- container doesn't exists
- zerodb process is not started

if it's the zerodb process and the container is still there, no problem.
If it's the container that needs to be recreated, then it could be that the `node_port` property on the zerdb_sal object changed, so we need to update it in the data of the service too.

**Comment by Pishoy** [comment]
verified 
```
In [183]: zdbOne.schedule_action('connection_info').wait().result
Out[183]: {'ip': '10.102.97.64', 'port': 9901, 'storage_ip': '10.102.97.64'}

In [184]: zdbTwo.schedule_action('connection_info').wait().result
Out[184]: {'ip': '10.102.97.64', 'port': 9902, 'storage_ip': '10.102.97.64'}

In [185]: zdbOne.schedule_action('namespace_create', args={'name':'firstNS'})
Out[185]: namespace_create

In [186]: zdbOne.schedule_action('namespace_list').wait().result
Out[186]: [{'name': 'firstNS', 'password': None, 'public': True, 'size': None}]


In [187]: zdbm.schedule_action('namespace_create', args={'name':'secondNS'})
Out[187]: namespace_create

In [188]: zdbTwo.schedule_action('namespace_create', args={'name':'secondNS'})
Out[188]: namespace_create

In [189]: zdbTwo.schedule_action('namespace_list').wait().result
Out[189]: [{'name': 'secondNS', 'password': None, 'public': True, 'size': None}]
In [200]: zdbOne.schedule_action('stop').wait(die=True)
Out[200]: stop

In [201]: node_client.client.container.list()
Out[201]: 
{'1': {'container': {'arguments': {'cgroups': [['devices', 'corex']],
    'config': None,
    'env': {'HOME': '/root', 'LANG': 'C.UTF-8', 'LC_ALL': 'C.UTF-8'},
    'host_network': False,
    'hostname': '',
    'identity': '',
    'mount': {'/var/cache/zrobot/config': '/opt/code/local/stdorg/config',
     '/var/cache/zrobot/data': '/opt/var/data/zrobot/zrobot_data',
     '/var/cache/zrobot/jsconfig': '/root/jumpscale/cfg',
     '/var/cache/zrobot/ssh': '/root/.ssh',
     '/var/run/redis.sock': '/tmp/redis.sock'},
    'name': 'zrobot',
    'nics': [{'config': {'cidr': '',
       'dhcp': False,
       'dns': None,
       'gateway': ''},
      'hwaddr': '',
      'id': '',
      'monitor': False,
      'state': 'configured',
      'type': 'default'}],
    'port': {'zt*:6600': 6600},
    'privileged': False,
    'root': 'https://hub.grid.tf/tf-autobuilder/threefoldtech-0-robot-autostart-development.flist',
    'storage': 'zdb://hub.grid.tf:9900',
    'tags': ['zrobot']},
   'pid': 438,
   'root': '/mnt/containers/1'},
  'cpu': 0,
  'rss': 7880704,
  'swap': 0,
  'vms': 300244992},
 '13': {'container': {'arguments': {'cgroups': [['devices', 'corex']],
    'config': {},
    'env': {},
    'host_network': False,
    'hostname': '',
    'identity': '6e708e5e2d:0:cfbb1b68bc81fdfa35cdeddeca13497776c442eca52502e7f5d67fef71fc935ecb57484aa65d59622cfcbd16516e7d5339da9322d353afea32d9b28f84017bd0:45a4b6755be7abd0796119594ad3f7c6c8e9ee0105e28a2b83c3b75f93399158a8580bfcaf44e7f10a9a78f5abad1e7c780e8631452ce2161035f2c90ea6b4d2',
    'mount': {'/mnt/storagepools/sdb2': '/zerodb'},
    'name': 'zerodb-two',
    'nics': [{'config': {'cidr': '',
       'dhcp': False,
       'dns': None,
       'gateway': ''},
      'hwaddr': '',
      'id': 'None',
      'monitor': False,
      'name': 'nat0',
      'state': 'configured',
      'type': 'default'}],
    'port': {'9902': 9900},
    'privileged': False,
    'root': 'https://hub.grid.tf/tf-autobuilder/threefoldtech-0-db-release-development.flist',
    'storage': 'zdb://hub.grid.tf:9900',
    'tags': ['zerodb-two']},
   'pid': 13533,
   'root': '/mnt/containers/13'},
  'cpu': 0.9241216916989229,
  'rss': 10371072,
  'swap': 0,
  'vms': 367353856}}
In [208]: node_client.client.container.terminate(15)

In [209]: node_client.client.container.list()
Out[209]: 
{'1': {'container': {'arguments': {'cgroups': [['devices', 'corex']],
    'config': None,
    'env': {'HOME': '/root', 'LANG': 'C.UTF-8', 'LC_ALL': 'C.UTF-8'},
    'host_network': False,
    'hostname': '',
    'identity': '',
    'mount': {'/var/cache/zrobot/config': '/opt/code/local/stdorg/config',
     '/var/cache/zrobot/data': '/opt/var/data/zrobot/zrobot_data',
     '/var/cache/zrobot/jsconfig': '/root/jumpscale/cfg',
     '/var/cache/zrobot/ssh': '/root/.ssh',
     '/var/run/redis.sock': '/tmp/redis.sock'},
    'name': 'zrobot',
    'nics': [{'config': {'cidr': '',
       'dhcp': False,
       'dns': None,
       'gateway': ''},
      'hwaddr': '',
      'id': '',
      'monitor': False,
      'state': 'configured',
      'type': 'default'}],
    'port': {'zt*:6600': 6600},
    'privileged': False,
    'root': 'https://hub.grid.tf/tf-autobuilder/threefoldtech-0-robot-autostart-development.flist',
    'storage': 'zdb://hub.grid.tf:9900',
    'tags': ['zrobot']},
   'pid': 438,
   'root': '/mnt/containers/1'},
  'cpu': 0,
  'rss': 7823360,
  'swap': 0,
  'vms': 300244992},
 '13': {'container': {'arguments': {'cgroups': [['devices', 'corex']],
    'config': {},
    'env': {},
    'host_network': False,
    'hostname': '',
    'identity': '6e708e5e2d:0:cfbb1b68bc81fdfa35cdeddeca13497776c442eca52502e7f5d67fef71fc935ecb57484aa65d59622cfcbd16516e7d5339da9322d353afea32d9b28f84017bd0:45a4b6755be7abd0796119594ad3f7c6c8e9ee0105e28a2b83c3b75f93399158a8580bfcaf44e7f10a9a78f5abad1e7c780e8631452ce2161035f2c90ea6b4d2',
    'mount': {'/mnt/storagepools/sdb2': '/zerodb'},
    'name': 'zerodb-two',
    'nics': [{'config': {'cidr': '',
       'dhcp': False,
       'dns': None,
       'gateway': ''},
      'hwaddr': '',
      'id': 'None',
      'monitor': False,
      'name': 'nat0',
      'state': 'configured',
      'type': 'default'}],
    'port': {'9902': 9900},
    'privileged': False,
    'root': 'https://hub.grid.tf/tf-autobuilder/threefoldtech-0-db-release-development.flist',
    'storage': 'zdb://hub.grid.tf:9900',
    'tags': ['zerodb-two']},
   'pid': 13533,
   'root': '/mnt/containers/13'},
  'cpu': 1.2299979546856021,
  'rss': 10625024,
  'swap': 0,
  'vms': 367353856},
 '16': {'container': {'arguments': {'cgroups': [['devices', 'corex']],
    'config': {},
    'env': {},
    'host_network': False,
    'hostname': '',
    'identity': '93c3be0513:0:fb8003061300a0fc4ed7e70c2dc914e9bebb8ecf942b9ae5f5d3e2984f3b446e0031f77577dd6920c0f60df95e99d29d2eba7d661940e0bd3e5b2fd1d631dfc5:af3a6b83f6781b7f709952e931f7f7664421cd751eae08301a5783e83ebd37f2dfdd8e43318b26b44d7b9b4bccc5520a332e684e142427668c1535aa2f34b6f9',
    'mount': {'/mnt/storagepools/sdb': '/zerodb'},
    'name': 'zerodb-one',
    'nics': [{'config': {'cidr': '',
       'dhcp': False,
       'dns': None,
       'gateway': ''},
      'hwaddr': '',
      'id': 'None',
      'monitor': False,
      'name': 'nat0',
      'state': 'configured',
      'type': 'default'}],
    'port': {'9901': 9900},
    'privileged': False,
    'root': 'https://hub.grid.tf/tf-autobuilder/threefoldtech-0-db-release-development.flist',
    'storage': 'zdb://hub.grid.tf:9900',
    'tags': ['zerodb-one']},
   'pid': 16993,
   'root': '/mnt/containers/16'},
  'cpu': 0,
  'rss': 6840320,
  'swap': 0,
  'vms': 289554432}}

In [210]: zdbOne.schedule_action('connection_info').wait().result
Out[210]: {'ip': '10.102.97.64', 'port': 9901, 'storage_ip': '10.102.97.64'}

In [211]: zdbOne.schedule_action('namespace_list').wait().result
Out[211]: [{'name': 'firstNS', 'password': None, 'public': True, 'size': None}]
```
##### js version 
```
0-robot
commit a15195e2d096d894ca09721a1b5cc37ada787700
Author: Christophe de Carvalho Pereira Martins <christophe.dcpm@gmail.com>
Date:   Fri Sep 14 09:32:42 2018 +0200

    change log level of noisy error
0-templates
commit d03401be880351c26cfa0814ae7fce272a1a3f18
Author: islamTaha12 <islamtaha2012@gmail.com>
Date:   Sun Sep 16 17:37:46 2018 +0200

    remove duplicate code
digital_me
commit ce832666ab2f688285575dc40fe2211837eb575d
Author: Abdulrahman Hamdy <arahman.hamdy91@gmail.com>
Date:   Mon Sep 10 13:28:36 2018 +0200

    Fix gedis client to be loaded from memory
digital_me_recipes
commit bf069534af15c75b89aaccdb502b2d53d1d7ed26
Author: despiegk <kristof@incubaid.com>
Date:   Sat Aug 18 11:27:36 2018 +0200

    new
jumpscale_core
commit 28515efa893162cfc08cc4e259bc268a4c48ef4d
Author: BolaNasr <bola.e.nasr@gmail.com>
Date:   Mon Sep 10 18:09:10 2018 +0200

    'Jumpscale' object has no attribute 'logging'
jumpscale_lib
commit b244d7d5b53fcb9e4b348b55faefab6a898ed6f7
Author: Christophe de Carvalho Pereira Martins <christophe.dcpm@gmail.com>
Date:   Tue Sep 18 11:37:44 2018 +0200

    zos sal: use public_addr when not storage network is configured
jumpscale_prefab
commit 44e92d0c9e47f663c1ede06e8d8c983905da581d
Author: Abdelrahman Hussein <ahussein.abdelrahman@gmail.com>
Date:   Sun Sep 9 15:08:07 2018 +0200

    update installtion of atomicswap prefab
```

**Comment by zaibon** [comment]
@Pishoy can you please take 5 minute when you do a report to write something useful instead of just dumping some logs like this. I don't see why you have to show the full output of the container data, that doesn't bring anything and it makes it really hard to see what you are actually trying to do.

But I see at some point you do: `node_client.client.container.terminate(15)`
While the container list doesn't show any container with id 15, so this line does nothing.
A clear test for this would be, you create your zerodb, your namespace.
then you stop all the containers
then you have a loop that compare port in the service schema and the port of the actual container.
You can write that pragmatically and have a proof that the bug is fixed. Now I need to spend 10 minute decrypting a dump of logs

**Comment by Pishoy** [comment]
@zaibon what you tell me about steps that what i did only i have missed the lines that has the container 15

**Comment by zaibon** [comment]
ok I see more clearly now. But you actually didn't tested anything yet. Both container 15 and 16 have the same port forwarder 9901, so you don't know if the template has properly updated it since it's the same for the 2 containers.  That's why I said better to stop all the container, so you have more chance that the new port forwarded will be different

**Comment by zaibon** [comment]
same problem as before the port forwarded didn't change so you still don't know if the template have updated the nodePort property properly

**Comment by Pishoy** [comment]
bug still exist as the zdb template data does not updated according the new ports when start the zdb containers 
```
In [75]: zdbOne.schedule_action('start').wait(die=True)
Out[75]: start

In [76]: zdbTwo.schedule_action('start').wait(die=True)
Out[76]: start

In [77]: node_client.client.container.list()

 '23': {'container': {'arguments': {'cgroups': [['devices', 'corex']],
    'config': {},
    'env': {},
    'host_network': False,
    'hostname': '',
    'identity': '93c3be0513:0:fb8003061300a0fc4ed7e70c2dc914e9bebb8ecf942b9ae5f5d3e2984f3b446e0031f77577dd6920c0f60df95e99d29d2eba7d661940e0bd3e5b2fd1d631dfc5:af3a6b83f6781b7f709952e931f7f7664421cd751eae08301a5783e83ebd37f2dfdd8e43318b26b44d7b9b4bccc5520a332e684e142427668c1535aa2f34b6f9',
    'mount': {'/mnt/storagepools/sdb': '/zerodb'},
    'name': 'zerodb-one',
    'nics': [{'config': {'cidr': '',
       'dhcp': False,
       'dns': None,
       'gateway': ''},
      'hwaddr': '',
      'id': 'None',
      'monitor': False,
      'name': 'nat0',
      'state': 'configured',
      'type': 'default'}],
    'port': {'9902': 9900},
    'privileged': False,
    'root': 'https://hub.grid.tf/tf-autobuilder/threefoldtech-0-db-release-development.flist',
    'storage': 'zdb://hub.grid.tf:9900',
    'tags': ['zerodb-one']},
   'pid': 3527,
   'root': '/mnt/containers/23'},
  'cpu': 0.23714623161312723,
  'rss': 7176192,
  'swap': 0,
  'vms': 288112640},
 '24': {'container': {'arguments': {'cgroups': [['devices', 'corex']],
    'config': {},
    'env': {},
    'host_network': False,
    'hostname': '',
    'identity': '6e708e5e2d:0:cfbb1b68bc81fdfa35cdeddeca13497776c442eca52502e7f5d67fef71fc935ecb57484aa65d59622cfcbd16516e7d5339da9322d353afea32d9b28f84017bd0:45a4b6755be7abd0796119594ad3f7c6c8e9ee0105e28a2b83c3b75f93399158a8580bfcaf44e7f10a9a78f5abad1e7c780e8631452ce2161035f2c90ea6b4d2',
    'mount': {'/mnt/storagepools/sdb2': '/zerodb'},
    'name': 'zerodb-two',
    'nics': [{'config': {'cidr': '',
       'dhcp': False,
       'dns': None,
       'gateway': ''},
      'hwaddr': '',
      'id': 'None',
      'monitor': False,
      'name': 'nat0',
      'state': 'configured',
      'type': 'default'}],
    'port': {'9903': 9900},
    'privileged': False,
    'root': 'https://hub.grid.tf/tf-autobuilder/threefoldtech-0-db-release-development.flist',
    'storage': 'zdb://hub.grid.tf:9900',
    'tags': ['zerodb-two']},
   'pid': 3604,
   'root': '/mnt/containers/24'},
  'cpu': 0.2371432598480226,
  'rss': 6709248,
  'swap': 0,
  'vms': 288112640}}

In [78]: zdbOne.data
Out[78]: 
{'data': {'admin': 'passworda',
  'diskType': 'hdd',
  'mode': 'user',
  'namespaces': [{'name': 'firstNS',
    'password': None,
    'public': True,
    'size': None}],
  'nics': [],
  'nodePort': 9901,
  'path': '/mnt/storagepools/sdb',
  'size': 0,
  'sync': True,
  'ztIdentity': '93c3be0513:0:fb8003061300a0fc4ed7e70c2dc914e9bebb8ecf942b9ae5f5d3e2984f3b446e0031f77577dd6920c0f60df95e99d29d2eba7d661940e0bd3e5b2fd1d631dfc5:af3a6b83f6781b7f709952e931f7f7664421cd751eae08301a5783e83ebd37f2dfdd8e43318b26b44d7b9b4bccc5520a332e684e142427668c1535aa2f34b6f9'},
 'guid': '1c1b32de-44ac-4259-b8b7-01aea522f4fc',
 'name': 'zerodb-one',
 'public': False,
 'state': [{'category': 'status', 'state': 'ok', 'tag': 'running'},
  {'category': 'actions', 'state': 'ok', 'tag': 'start'},
  {'category': 'actions', 'state': 'ok', 'tag': 'install'}],
 'template': 'github.com/threefoldtech/0-templates/zerodb/0.0.1',
 'version': '0.0.1'}

In [81]: zdbTwo.data
Out[81]: 
{'data': {'admin': 'passworda',
  'diskType': 'hdd',
  'mode': 'user',
  'namespaces': [{'name': 'secondNS',
    'password': None,
    'public': True,
    'size': None}],
  'nics': [],
  'nodePort': 9902,
  'path': '/mnt/storagepools/sdb2',
  'size': 0,
  'sync': True,
  'ztIdentity': '6e708e5e2d:0:cfbb1b68bc81fdfa35cdeddeca13497776c442eca52502e7f5d67fef71fc935ecb57484aa65d59622cfcbd16516e7d5339da9322d353afea32d9b28f84017bd0:45a4b6755be7abd0796119594ad3f7c6c8e9ee0105e28a2b83c3b75f93399158a8580bfcaf44e7f10a9a78f5abad1e7c780e8631452ce2161035f2c90ea6b4d2'},
 'guid': 'b40b1e5a-7340-4805-835b-7f6ca3fd4f96',
 'name': 'zerodb-two',
 'public': False,
 'state': [{'category': 'status', 'state': 'ok', 'tag': 'running'},
  {'category': 'actions', 'state': 'ok', 'tag': 'start'},
  {'category': 'actions', 'state': 'ok', 'tag': 'install'}],
 'template': 'github.com/threefoldtech/0-templates/zerodb/0.0.1',
 'version': '0.0.1'}

```
also connection_info is different than the template data 

```
In [83]: zdbOne.data['data']['nodePort']
Out[83]: 9901

In [84]: zdbTwo.data['data']['nodePort']
Out[84]: 9902

In [85]: zdbOne.schedule_action('connection_info').wait().result
Out[85]: {'ip': '10.102.97.64', 'port': 9902, 'storage_ip': '10.102.97.64'}

In [86]: zdbTwo.schedule_action('connection_info').wait().result
Out[86]: {'ip': '10.102.97.64', 'port': 9903, 'storage_ip': '10.102.97.64'}

```

**Comment by Pishoy** [comment]
verified 
```
In [77]: zdbfour.schedule_action('start').wait(die=True)
Out[77]: start
In [78]: node_client.client.container.list()

 '8': {'container': {'arguments': {'cgroups': [['devices', 'corex']],
    'config': {},
    'env': {},
    'host_network': False,
    'hostname': '',
    'identity': '5dfcd2c3d6:0:b777703f5811a919c92c3787b7f7f3e019b3ac2807df84f3cb5726346e2c0622bae4fe39f76a6864fdb37d4c9946da29e967ed0a9c1dcfc9951f51614458c0f6:625ff4e51307ba8937a0c5c3ffdae203ed924448b592856a36e0a157f31a3a51903276dc83e305debcf484f2e7d3e15cac1e9b3c55d5efabbd6499dfb49b8610',
    'mount': {'/mnt/zdbs/sdc': '/zerodb'},
    'name': 'zdbfour',
    'nics': [{'config': {'cidr': '',
       'dhcp': False,
       'dns': None,
       'gateway': ''},
      'hwaddr': '',
      'id': 'None',
      'monitor': False,
      'name': 'nat0',
      'state': 'configured',
      'type': 'default'}],
    'port': {'9906': 9900},
    'privileged': False,
    'root': 'https://hub.grid.tf/tf-autobuilder/threefoldtech-0-db-release-development.flist',
    'storage': 'zdb://hub.grid.tf:9900',
    'tags': ['zdbfour']},
   'pid': 14764,
   'root': '/mnt/containers/8'},
  'cpu': 0,
  'rss': 7024640,
  'swap': 0,
  'vms': 365580288}}

In [79]: zdbfour.data['data']['nodePort']
Out[79]: 9901

In [80]: zdbfour.schedule_action('connection_info').wait(die=True).result
Out[80]: {'ip': '10.102.53.47', 'port': 9906, 'storage_ip': '10.102.53.47'}

In [81]: robot.services.names
Out[81]: 
{'_node_capacity': robot://zdb/github.com/threefoldtech/0-templates/node_capacity/0.0.1?guid=8ac485f1-b2e6-4ef7-8aae-77bcc913b542&name=_node_capacity,
 'namespace_four': robot://zdb/github.com/threefoldtech/0-templates/namespace/0.0.1?guid=a0e6ad7c-97af-4205-b2d7-ee9e55398e3a&name=namespace_four,
 'zdbfive': robot://zdb/github.com/threefoldtech/0-templates/zerodb/0.0.1?guid=2d476755-1646-41c3-a204-f7935b4c109d&name=zdbfive,
 'zdbfour': robot://zdb/github.com/threefoldtech/0-templates/zerodb/0.0.1?guid=75db4cd6-2c89-42d8-b054-6b870f138ac6&name=zdbfour}

In [83]: zdb4 = robot.services.get(name='zdbfour')
In [85]: zdb4.data['data']['nodePort']
Out[85]: 9906
```
